### ISSUE TITLE
ERROR -- : incompatible character encodings: ASCII-8BIT and UTF-8 (Encoding::CompatibilityError)

### ISSUE THREAD

**Issue by davidjuin0519** [boazsegev/plezi#17]
Hi Bo, 
When I was trying to render chinese character from db, this error always pops out:
```
E, [2016-02-04T17:30:09.803387 #3] ERROR -- : incompatible character encodings: ASCII-8BIT and UTF-8 (Encoding::CompatibilityError)
2016-02-04T17:31:51.954972+00:00 app[web.1]: (erb):241:in `concat'
2016-02-04T17:31:51.954972+00:00 app[web.1]: (erb):241:in `render'
2016-02-04T17:31:51.954973+00:00 app[web.1]: /app/vendor/ruby-2.2.3/lib/ruby/2.2.0/erb.rb:863:in `eval'
2016-02-04T17:31:51.954973+00:00 app[web.1]: /app/vendor/ruby-2.2.3/lib/ruby/2.2.0/erb.rb:863:in `result'
2016-02-04T17:31:51.954975+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/plezi-0.12.21/lib/plezi/common/renderer.rb:119:in `block in <module:Plezi>'
2016-02-04T17:31:51.954975+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/plezi-0.12.21/lib/plezi/common/renderer.rb:36:in `call'
2016-02-04T17:31:51.954976+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/plezi-0.12.21/lib/plezi/common/renderer.rb:36:in `block in render'
2016-02-04T17:31:51.954977+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/plezi-0.12.21/lib/plezi/common/renderer.rb:36:in `each'
2016-02-04T17:31:51.954978+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/plezi-0.12.21/lib/plezi/common/renderer.rb:36:in `render'
2016-02-04T17:31:51.954978+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/plezi-0.12.21/lib/plezi/handlers/controller_magic.rb:196:in `render'
2016-02-04T17:31:51.954979+00:00 app[web.1]: /app/config/initializers/websocket.rb:32:in `index'
2016-02-04T17:31:51.954980+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/plezi-0.12.21/lib/plezi/handlers/controller_core.rb:88:in `_route_path_to_methods_and_set_the_response_'
2016-02-04T17:31:51.954980+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/plezi-0.12.21/lib/plezi/handlers/route.rb:23:in `on_request'
2016-02-04T17:31:51.954981+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/plezi-0.12.21/lib/plezi/handlers/http_router.rb:84:in `block in call'
2016-02-04T17:31:51.954982+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/plezi-0.12.21/lib/plezi/handlers/http_router.rb:84:in `each'
2016-02-04T17:31:51.954982+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/plezi-0.12.21/lib/plezi/handlers/http_router.rb:84:in `call'
2016-02-04T17:31:51.954983+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/iodine-0.1.21/lib/iodine/http/rack_support.rb:19:in `call'
2016-02-04T17:31:51.954983+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/iodine-0.1.21/lib/iodine/http/http1.rb:187:in `dispatch'
2016-02-04T17:31:51.954984+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/iodine-0.1.21/lib/iodine/http/http1.rb:97:in `on_message'
2016-02-04T17:31:51.954985+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/iodine-0.1.21/lib/iodine/protocol.rb:188:in `call'
2016-02-04T17:31:51.954986+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/iodine-0.1.21/lib/iodine/core.rb:65:in `work'
2016-02-04T17:31:51.954986+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/iodine-0.1.21/lib/iodine/core.rb:55:in `cycle'
2016-02-04T17:31:51.954987+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/iodine-0.1.21/lib/iodine/core.rb:75:in `block (2 levels) in startup'
```
I am pretty sure that the string is encoded in UTF-8...I got no idea why this error occur...
Do you have any idea?

**Comment by boazsegev** [comment]
Could you post the full error log's backtrace?

The backtrace gives the file names and line numbers , so it makes it easier to look and see where the issue might be and what might have caused this error.

**Comment by davidjuin0519** [comment]
Hi Bo, sorry for missing the trace. I updated.

**Comment by boazsegev** [comment]
The backtrace shows that the ERB renderer (which is part of the Ruby standard library) is the one failing.

Can you try updating the template to write the encoding of the DB string instead of the string itself (change the `data` to `data.encoding.to_s`)? - this will help make sure that the database returns a UTF-8 encoded string.

Also, could you post the code you use for rendering (in the controller) and the code you use in the template?

**Comment by davidjuin0519** [comment]
Hi Bo, 
Ii works when I change `data` to `data.encoding.to_s`. in my use case, if I detected chinese characters I will replace them with English words. Somehow not good solution.

My code is something like this:
```ruby
#websocket.rb
def get_user
  @user = User.find(uid)
end

#chat.html.erb
<%= @user.name %>
```

**Comment by boazsegev** [comment]
What was the encoding you got? UTF-8?

If so, maybe we need to tweak the way Plezi is calling the ERB rendering engine.

**Comment by boazsegev** [comment]
The rendering engine in Plezi is based on a "plugin" design.

Maybe try changing the ERB renderer using the following code:

```ruby
	Renderer.register :erb do |filename, context, &block|
		next unless defined? ::ERB
		( Plezi.cache_needs_update?(filename) ? Plezi.cache_data( filename, ( ERB.new( IO.binread(filename).force_encoding("UTF-8")  ) ) )  : (Plezi.get_cached filename) ).result((context) , &block)
	end
```

Let me know if it helps.

**Comment by davidjuin0519** [comment]
Hi Bo, 
Yes it is UTF-8. Where should I implement this snippet of code? Thank you.

**Comment by boazsegev** [comment]
Put it somewhere in the application, it's not very important where... maybe the end of the routes file.

**Comment by boazsegev** [comment]
Please let me know if it works, so I can patch the gem and release an update.

**Comment by davidjuin0519** [comment]
Hi Bo, 
It works! Thank you!

**Comment by boazsegev** [comment]
Thank you Juin Chiu for your help discovering this issue! 👍🏻
