### ISSUE TITLE
Rack < 2.0 : cannot load such file -- rack/query_parser.rb

### ISSUE THREAD

**Issue by jericdeleon** [boazsegev/plezi#29]
Trying plezi out for a Rails 4.2 app.
I took out Puma, and Iodine is now supposed to take over as the web server.
Unfortunately `rails server` returns with the issue:

<details>
  <summary>rails s error:</summary>

```
/home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require': cannot load such file -- rack/query_parser.rb (LoadError)
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/plezi-0.14.2/lib/plezi/router/route.rb:4:in `<top (required)>'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/plezi-0.14.2/lib/plezi/router/router.rb:1:in `<top (required)>'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/plezi-0.14.2/lib/plezi/helpers.rb:2:in `<top (required)>'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/plezi-0.14.2/lib/plezi/api.rb:2:in `<top (required)>'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/plezi-0.14.2/lib/plezi.rb:4:in `<top (required)>'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `require'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `each'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `block in require'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `each'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `require'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler.rb:114:in `require'
        from /home/jericdeleon/Documents/projects/dentca/code/sales-store/backend/config/application.rb:7:in `<top (required)>'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:78:in `require'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:78:in `block in server'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:75:in `tap'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:75:in `server'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
        from /home/jericdeleon/Documents/projects/dentca/code/sales-store/backend/bin/rails:9:in `require'
        from /home/jericdeleon/Documents/projects/dentca/code/sales-store/backend/bin/rails:9:in `<top (required)>'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from /home/jericdeleon/.rbenv/versions/2.3.6/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from /home/jericdeleon/Documents/projects/dentca/code/sales-store/backend/bin/spring:15:in `<top (required)>'
        from bin/rails:3:in `load'
        from bin/rails:3:in `<main>'
```
</details>

<br/>

Can I ask for any ideas on what to investigate / try next?
This level of error is currently too cryptic for me :(

Here are my gemfiles:

<details>
  <summary>Gemfile</summary>

```
source 'https://rubygems.org'

group :development, :test do
  # use 'dotenv-rails' for development/test environment variables
  gem 'dotenv-rails'
end

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.6'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Locking i18n gem version
gem 'i18n', '~> 0.7.0'

# Use Spree
gem 'spree', '3.1.3'
gem 'spree_auth_devise', '3.1.0'
gem 'spree_gateway', '~> 3.3'
gem 'active_model_serializers'

# Use Spree extensions
gem 'spree_mail_settings', github: 'spree-contrib/spree_mail_settings', branch: '3-1-stable'
gem 'spree_editor', github: 'spree-contrib/spree_editor', branch: '3-1-stable'
gem 'spree_print_invoice', github: 'spree-contrib/spree_print_invoice', branch: 'master'

# lock Kaminari to avoid: undefined method num_pages on Spree::Product
# gem 'kaminari', '~> 0.17.0'

# Use AWS for Paperclip's backend
# Paperclip 4 requires aws-sdk < 2; see: https://github.com/thoughtbot/paperclip/wiki/Upgrade-Paperclip-4x-to-5x
gem 'aws-sdk', '< 2.0'

# Use pg as the database for Active Record
gem 'pg', '~> 0.21'

# Use a null database adapter to run rake assets:precompile without database (docker build)
gem "activerecord-nulldb-adapter"  

# Rack Cores
gem 'rack-cors', :require => 'rack/cors'
gem 'rmagick'

# dentca-lab-specific gems
# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
# gem 'aws-sdk', '< 2.0'
gem 'seed_dump'

# gem 'sidekiq'
gem 'sucker_punch'

# hunt for n+1 queries
gem 'bullet'

gem 'plezi'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  gem 'pry'

  # use xray-rails to see template outlines
  gem 'xray-rails'

  # use 'sequel' to retrieve migrate sqlite data to pg
  gem 'sequel'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'

  # IDE gems: vscode-ruby
  gem 'ruby-debug-ide'
  gem 'debase'
  gem 'rubocop'
  gem 'solargraph'
  gem 'ripper-tags'
end

group :ist, :uat, :production do
  gem 'rails_12factor'

  # sentry
  gem 'sentry-raven'

  # instrumental
  gem 'instrumental_agent'
end
```
</details>

<details>
  <summary>Gemfile.lock</summary>

```
GIT
  remote: git://github.com/spree-contrib/spree_editor.git
  revision: 702db404e959d6c4fa42fc7c7ea48a28f6bd2d1e
  branch: 3-1-stable
  specs:
    spree_editor (3.1.0)
      ckeditor (~> 4.1.2)
      spree_backend (~> 3.1.0.beta)
      tinymce-rails (~> 4.2.5)

GIT
  remote: git://github.com/spree-contrib/spree_mail_settings.git
  revision: e292a7e843e80ddf0337c68ed4093c702ee60f62
  branch: 3-1-stable
  specs:
    spree_mail_settings (3.1.0)
      spree_backend (~> 3.1.0.beta)

GIT
  remote: git://github.com/spree-contrib/spree_print_invoice.git
  revision: e99527a241bbc6d91ba2f4c3b851c8dc68d70310
  branch: master
  specs:
    spree_print_invoice (3.0.0.beta)
      prawn-rails (~> 0.1.1)
      spree_core (>= 3.1.0, < 4.0)
      spree_extension

GEM
  remote: https://rubygems.org/
  specs:
    actionmailer (4.2.6)
      actionpack (= 4.2.6)
      actionview (= 4.2.6)
      activejob (= 4.2.6)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.6)
      actionview (= 4.2.6)
      activesupport (= 4.2.6)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (4.2.6)
      activesupport (= 4.2.6)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    active_model_serializers (0.10.7)
      actionpack (>= 4.1, < 6)
      activemodel (>= 4.1, < 6)
      case_transform (>= 0.2)
      jsonapi-renderer (>= 0.1.1.beta1, < 0.3)
    activejob (4.2.6)
      activesupport (= 4.2.6)
      globalid (>= 0.3.0)
    activemerchant (1.77.0)
      activesupport (>= 3.2.14, < 6.x)
      builder (>= 2.1.2, < 4.0.0)
      i18n (>= 0.6.9)
      nokogiri (~> 1.4)
    activemodel (4.2.6)
      activesupport (= 4.2.6)
      builder (~> 3.1)
    activerecord (4.2.6)
      activemodel (= 4.2.6)
      activesupport (= 4.2.6)
      arel (~> 6.0)
    activerecord-nulldb-adapter (0.3.8)
      activerecord (>= 2.0.0)
    activesupport (4.2.6)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    acts_as_list (0.7.2)
      activerecord (>= 3.0)
    addressable (2.5.2)
      public_suffix (>= 2.0.2, < 4.0)
    arel (6.0.4)
    ast (2.4.0)
    autoprefixer-rails (7.2.5)
      execjs
    awesome_nested_set (3.0.3)
      activerecord (>= 4.0.0, < 5)
    aws-sdk (1.67.0)
      aws-sdk-v1 (= 1.67.0)
    aws-sdk-v1 (1.67.0)
      json (~> 1.4)
      nokogiri (~> 1)
    bcrypt (3.1.11)
    binding_of_caller (0.8.0)
      debug_inspector (>= 0.0.1)
    bootstrap-sass (3.3.7)
      autoprefixer-rails (>= 5.2.1)
      sass (>= 3.3.4)
    builder (3.2.3)
    bullet (5.7.6)
      activesupport (>= 3.0.0)
      uniform_notifier (~> 1.11.0)
    byebug (10.0.0)
    camertron-eprun (1.1.1)
    cancancan (1.10.1)
    canonical-rails (0.0.11)
      rails (>= 3.1, < 5.0)
    carmen (1.0.2)
      activesupport (>= 3.0.0)
    case_transform (0.2)
      activesupport
    ckeditor (4.1.6)
      cocaine
      orm_adapter (~> 0.5.0)
    cldr-plurals-runtime-rb (1.0.1)
    climate_control (0.2.0)
    cocaine (0.5.8)
      climate_control (>= 0.0.3, < 1.0)
    coderay (1.1.2)
    coffee-rails (4.1.1)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.1.x)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.12.2)
    colorize (0.8.1)
    concurrent-ruby (1.0.5)
    crass (1.0.3)
    css_parser (1.6.0)
      addressable
    debase (0.2.2)
      debase-ruby_core_source (>= 0.10.2)
    debase-ruby_core_source (0.10.2)
    debug_inspector (0.0.3)
    deface (1.0.2)
      colorize (>= 0.5.8)
      nokogiri (~> 1.6.0)
      polyglot
      rails (>= 3.1)
    devise (3.5.10)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      responders
      thread_safe (~> 0.1)
      warden (~> 1.2.3)
    devise-encryptable (0.1.2)
      devise (>= 2.1.0)
    dotenv (2.2.1)
    dotenv-rails (2.2.1)
      dotenv (= 2.2.1)
      railties (>= 3.2, < 5.2)
    erubis (2.7.0)
    execjs (2.7.0)
    faraday (0.15.3)
      multipart-post (>= 1.2, < 3)
    ffaker (2.2.0)
    ffi (1.9.21)
    font-awesome-rails (4.7.0.3)
      railties (>= 3.2, < 5.2)
    friendly_id (5.1.0)
      activerecord (>= 4.0.0)
    globalid (0.4.1)
      activesupport (>= 4.2.0)
    highline (1.6.21)
    htmlentities (4.3.4)
    i18n (0.7.0)
    instrumental_agent (2.1.0)
      metrician
    iodine (0.7.5)
      rack (>= 1.0, < 3.0)
    jbuilder (2.7.0)
      activesupport (>= 4.2.0)
      multi_json (>= 1.2)
    jquery-rails (4.3.1)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    jquery-ui-rails (5.0.5)
      railties (>= 3.2.16)
    json (1.8.6)
    jsonapi-renderer (0.2.0)
    kaminari (0.17.0)
      actionpack (>= 3.0.0)
      activesupport (>= 3.0.0)
    libv8 (3.16.14.19)
    loofah (2.1.1)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.0)
      mini_mime (>= 0.1.1)
    method_source (0.9.0)
    metrician (0.1.0)
    mime-types (3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2016.0521)
    mimemagic (0.3.0)
    mini_mime (1.0.0)
    mini_portile2 (2.1.0)
    minitest (5.11.3)
    monetize (1.7.0)
      money (~> 6.9)
    money (6.10.1)
      i18n (>= 0.6.4, < 1.0)
    multi_json (1.13.1)
    multipart-post (2.0.0)
    nokogiri (1.6.8.1)
      mini_portile2 (~> 2.1.0)
    orm_adapter (0.5.0)
    paperclip (4.3.7)
      activemodel (>= 3.2.0)
      activesupport (>= 3.2.0)
      cocaine (~> 0.5.5)
      mime-types
      mimemagic (= 0.3.0)
    parallel (1.12.1)
    paranoia (2.1.5)
      activerecord (~> 4.0)
    parser (2.4.0.2)
      ast (~> 2.3)
    pdf-core (0.7.0)
    pg (0.21.0)
    plezi (0.14.2)
      iodine (~> 0.2, >= 0.2.1)
    polyamorous (1.3.3)
      activerecord (>= 3.0)
    polyglot (0.3.5)
    powerpack (0.1.2)
    prawn (2.2.2)
      pdf-core (~> 0.7.0)
      ttfunk (~> 1.5)
    prawn-rails (0.1.1)
      prawn
      prawn-table
      rails (>= 3.1.0)
    prawn-table (0.2.2)
      prawn (>= 1.3.0, < 3.0.0)
    premailer (1.11.1)
      addressable
      css_parser (>= 1.6.0)
      htmlentities (>= 4.0.0)
    premailer-rails (1.10.1)
      actionmailer (>= 3, < 6)
      premailer (~> 1.7, >= 1.7.9)
    pry (0.11.3)
      coderay (~> 1.1.0)
      method_source (~> 0.9.0)
    public_suffix (3.0.1)
    rabl (0.12.0)
      activesupport (>= 2.3.14)
    rack (1.6.8)
    rack-cors (1.0.2)
    rack-protection (1.5.3)
      rack
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.2.6)
      actionmailer (= 4.2.6)
      actionpack (= 4.2.6)
      actionview (= 4.2.6)
      activejob (= 4.2.6)
      activemodel (= 4.2.6)
      activerecord (= 4.2.6)
      activesupport (= 4.2.6)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.6)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.9)
      activesupport (>= 4.2.0, < 5.0)
      nokogiri (~> 1.6)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.3)
      loofah (~> 2.0)
    rails_12factor (0.0.3)
      rails_serve_static_assets
      rails_stdout_logging
    rails_serve_static_assets (0.0.5)
    rails_stdout_logging (0.0.5)
    railties (4.2.6)
      actionpack (= 4.2.6)
      activesupport (= 4.2.6)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rainbow (3.0.0)
    rake (12.3.0)
    ransack (1.4.1)
      actionpack (>= 3.0)
      activerecord (>= 3.0)
      activesupport (>= 3.0)
      i18n
      polyamorous (~> 1.1)
    rb-fsevent (0.10.2)
    rb-inotify (0.9.10)
      ffi (>= 0.5.0, < 2)
    rdoc (4.3.0)
    ref (2.0.0)
    responders (2.4.0)
      actionpack (>= 4.2.0, < 5.3)
      railties (>= 4.2.0, < 5.3)
    ripper-tags (0.6.0)
    rmagick (2.16.0)
    rubocop (0.52.1)
      parallel (~> 1.10)
      parser (>= 2.4.0.2, < 3.0)
      powerpack (~> 0.1)
      rainbow (>= 2.2.2, < 4.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (~> 1.0, >= 1.0.1)
    ruby-debug-ide (0.6.0)
      rake (>= 0.8.1)
    ruby-progressbar (1.9.0)
    sass (3.5.5)
      sass-listen (~> 4.0.0)
    sass-listen (4.0.0)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    sass-rails (5.0.7)
      railties (>= 4.0.0, < 6)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    sdoc (0.4.2)
      json (~> 1.7, >= 1.7.7)
      rdoc (~> 4.0)
    seed_dump (3.2.4)
      activerecord (>= 4)
      activesupport (>= 4)
    select2-rails (3.5.9.1)
      thor (~> 0.14)
    sentry-raven (2.7.4)
      faraday (>= 0.7.6, < 1.0)
    sequel (5.5.0)
    sinatra (1.4.8)
      rack (~> 1.5)
      rack-protection (~> 1.4)
      tilt (>= 1.3, < 3)
    solargraph (0.10.3)
      parser (~> 2.4)
      sinatra (~> 1.4)
      thor (~> 0.19, >= 0.19.4)
      yard (~> 0.9)
    spree (3.1.3)
      spree_api (= 3.1.3)
      spree_backend (= 3.1.3)
      spree_cmd (= 3.1.3)
      spree_core (= 3.1.3)
      spree_frontend (= 3.1.3)
      spree_sample (= 3.1.3)
    spree_api (3.1.3)
      rabl (~> 0.12.0)
      spree_core (= 3.1.3)
      versioncake (~> 2.3.1)
    spree_auth_devise (3.1.0)
      devise (~> 3.5.4)
      devise-encryptable (= 0.1.2)
      spree_core (~> 3.1.0.beta)
    spree_backend (3.1.3)
      bootstrap-sass (~> 3.3)
      jquery-rails (~> 4.1)
      jquery-ui-rails (~> 5.0)
      select2-rails (= 3.5.9.1)
      spree_api (= 3.1.3)
      spree_core (= 3.1.3)
    spree_cmd (3.1.3)
      thor (~> 0.14)
    spree_core (3.1.3)
      activemerchant (~> 1.59)
      acts_as_list (= 0.7.2)
      awesome_nested_set (~> 3.0.1)
      cancancan (~> 1.10.1)
      carmen (~> 1.0.0)
      deface (~> 1.0.0)
      ffaker (~> 2.2.0)
      font-awesome-rails (~> 4.0)
      friendly_id (~> 5.1.0)
      highline (~> 1.6.18)
      kaminari (~> 0.17)
      monetize (~> 1.1)
      paperclip (~> 4.3.0)
      paranoia (~> 2.1.0)
      premailer-rails
      rails (~> 4.2.5)
      ransack (~> 1.4.1)
      responders
      sprockets-rails
      state_machines-activerecord (~> 0.2)
      stringex
      truncate_html (~> 0.9.3)
      twitter_cldr (~> 3.0)
    spree_extension (0.0.5)
      activerecord (>= 4.2)
    spree_frontend (3.1.3)
      bootstrap-sass (>= 3.3.5.1, < 3.4)
      canonical-rails (~> 0.0.4)
      jquery-rails (~> 4.1)
      spree_api (= 3.1.3)
      spree_core (= 3.1.3)
    spree_gateway (3.3.2)
      spree_core (>= 3.1.0, < 4.0)
      spree_extension
    spree_sample (3.1.3)
      spree_core (= 3.1.3)
    spring (2.0.2)
      activesupport (>= 4.2)
    sprockets (3.7.1)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.1)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    state_machines (0.5.0)
    state_machines-activemodel (0.5.0)
      activemodel (>= 4.1, < 5.2)
      state_machines (>= 0.5.0)
    state_machines-activerecord (0.5.0)
      activerecord (>= 4.1, < 5.2)
      state_machines-activemodel (>= 0.5.0)
    stringex (2.8.2)
    sucker_punch (2.1.1)
      concurrent-ruby (~> 1.0)
    therubyracer (0.12.3)
      libv8 (~> 3.16.14.15)
      ref
    thor (0.20.0)
    thread_safe (0.3.6)
    tilt (2.0.8)
    tinymce-rails (4.2.8)
      railties (>= 3.1.1)
    truncate_html (0.9.3)
    ttfunk (1.5.1)
    turbolinks (5.1.0)
      turbolinks-source (~> 5.1)
    turbolinks-source (5.1.0)
    twitter_cldr (3.6.0)
      camertron-eprun
      cldr-plurals-runtime-rb (~> 1.0)
      tzinfo
    tzinfo (1.2.5)
      thread_safe (~> 0.1)
    uglifier (4.1.5)
      execjs (>= 0.3.0, < 3)
    unicode-display_width (1.4.0)
    uniform_notifier (1.11.0)
    versioncake (2.3.1)
      actionpack (>= 3.2)
      activesupport (>= 3.2)
      railties (>= 3.2)
      tzinfo
    warden (1.2.7)
      rack (>= 1.0)
    web-console (2.3.0)
      activemodel (>= 4.0)
      binding_of_caller (>= 0.7.2)
      railties (>= 4.0)
      sprockets-rails (>= 2.0, < 4.0)
    xray-rails (0.3.1)
      rails (>= 3.1.0)
    yard (0.9.12)

PLATFORMS
  ruby

DEPENDENCIES
  active_model_serializers
  activerecord-nulldb-adapter
  aws-sdk (< 2.0)
  bullet
  byebug
  coffee-rails (~> 4.1.0)
  debase
  dotenv-rails
  i18n (~> 0.7.0)
  instrumental_agent
  jbuilder (~> 2.0)
  jquery-rails
  pg (~> 0.21)
  plezi
  pry
  rack-cors
  rails (= 4.2.6)
  rails_12factor
  ripper-tags
  rmagick
  rubocop
  ruby-debug-ide
  sass-rails (~> 5.0)
  sdoc (~> 0.4.0)
  seed_dump
  sentry-raven
  sequel
  solargraph
  spree (= 3.1.3)
  spree_auth_devise (= 3.1.0)
  spree_editor!
  spree_gateway (~> 3.3)
  spree_mail_settings!
  spree_print_invoice!
  spring
  sucker_punch
  therubyracer
  turbolinks
  tzinfo-data
  uglifier (>= 1.3.0)
  web-console (~> 2.0)
  xray-rails

BUNDLED WITH
   1.16.3
```
</details>

<br/>

Thank you for your time!

**Comment by boazsegev** [comment]
Hi @jericdeleon ,

I just skimmed the error log and gemfiles, looking for the source of the issue.

It seems like it might be a Rack version requirement isn't properly stated. Plezi might be assuming Rack `>= 2.0`. I'll keep digging.

You can still use Raw WebSockets and many of the features offered by Iodine directly, but I think Plezi might require a newer version of Rack (and, by consequence, Rails).

As a side note, consider starting up the app using:

```bash
bundle exec iodine -t 16 -w 1 -www ./public
```

(change the concurrency settings and static file service to fit your needs and maybe update any other settings you might require).

Kindly,
   Bo.
