### ISSUE TITLE
Help needed!

### ISSUE THREAD

**Issue by khataev** [boazsegev/plezi#34]
Hello! 
I do not understand how to use sample chat room code you have as an example ((( I started server:

```sh
→ ruby chat.rb
Running Plezi version: 0.16.4
Iodine.listen2http is deprecated, use Iodine.listen(service: :http).
WARNING: :app is deprecated in Iodine.listen and Iodine.connect. Use :handler
INFO: Listening on port 3000
```

 but when I'm trying to connect to it via js websockets:

```js
ws = new WebSocket("ws://localhost:3000")
```

I get an error from server:

```
ERROR: Iodine caught an unprotected exception - ArgumentError: a target (:to) subject / stream / channel is required.
/Users/khataev/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/plezi-0.16.4/lib/plezi/controller/controller.rb:162:in `subscribe'
/Users/khataev/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/plezi-0.16.4/lib/plezi/controller/controller.rb:162:in `subscribe'
chat.rb:8:in `on_open'
/Users/khataev/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/plezi-0.16.4/lib/plezi/controller/bridge.rb:19:in `on_open'
```

**Comment by boazsegev** [comment]
Hi @khataev ,

Thank you for opening this issue.

It seems that the example code in `examples/chat.rb` is outdated.

I'm not sure why the named arguments don't work or at which point (version) did the code break, but generally speaking, the updated code should look like this:


```ruby
# finish with `exit` if running within `irb`
require 'plezi'
class ChatServer
  def index
    "Use Websockets to connect."
  end
  def on_open
    return close unless params['id']
    @name = params['id']
    subscribe :chat
    publish "chat", "#{@name} joind the chat."
    write "Welcome, #{@name}!"
    # if we have Redis
    if(Iodine::PubSub.default.is_a? Iodine::PubSub::Redis)
      # We'll add the name to the list of people in the chat.
      # Blocks are used as event callbacks and are executed asynchronously.
      Iodine::PubSub.default.send("SADD", "chat_members", @name) do
        # after the name was added, we'll get all the current people in the chat
        Iodine::PubSub.default.send("SMEMBERS", "chat_members") do |members|
          # By now, we're outside the Websocket connection's lock.
          # To safely access the connection, we'll use `defer`
          write "Currently in the chatroom: #{members.join ', '}"
        end
      end
    end
  end
  def on_close
    publish "chat", "#{@name} joind the chat."
    # if we have Redis
    Iodine::PubSub.default.send("SREM", "chat_members", @name) if(Iodine::PubSub.default.is_a? Iodine::PubSub::Redis)
  end
  def on_message data
    publish "chat", "#{@name}: #{data}"
  end
end
path_to_client = File.expand_path( File.dirname(__FILE__) )
Plezi.templates = path_to_client
Plezi.route '/', ChatServer
```

As you can see:

1. the named arguments (i.e., `channel: "chat"`) were replaced with simple arguments (`:chat` or `"chat"` would do).

2. the `Iodine.default_pubsub` method (pre 0.7.x API) was replaced: `Iodine::PubSub.default`

As for connecting to the example server, please add a username to the path. i.e.:

```js
ws = new WebSocket("ws://localhost:3000/Joe");
```
